### ISSUE TITLE
你好，为啥我启动后都失败了，可否给个使用方法？

### ISSUE THREAD

**Issue by knlvz** [bettermanbao/erx-shadowsocks-libev#2]
之前的问题解决了，权限没给对，但是启动后发现还是无法上，是哪儿出问题了？

![3333](https://user-images.githubusercontent.com/24656185/36947441-8fdcabfa-2006-11e8-94d3-0030ca7b20c4.jpg)
![2222](https://user-images.githubusercontent.com/24656185/36947443-967714c8-2006-11e8-8cdf-a1853c253fbf.jpg)

**Comment by bettermanbao** [comment]
你没开启root账号，不过没关系。
试试 pdnsd.conf 里的 run_as="root"; 改成 run_as="ubnt"; 应该可以解决。

**Comment by knlvz** [comment]
这个我把pdnsd.conf的所有者改成root可以启动了，但是还是无法上，电脑的dns和路由的dns需要设置成哪个？

**Comment by bettermanbao** [comment]
windows下用管理员权限运行一下ipconfig /flushdns，或者重启一下电脑。再试试。

**Comment by knlvz** [comment]
依旧是不是dns哪儿设置有问题了？

我之前的resolv.conf文件里面的nameserver 是114.114.114.114，替换成你的文件127.0.0.1跟这个有关系嘛

**Comment by bettermanbao** [comment]
教程，大概是这样吧。
* 所有文件复制对应目录。
* bin和init.d目录下的文件chmod +x一下，赋予执行权限
* update-rc.d shadowsocks enable，开机自动运行。

我是用root用户直接装的，所以没有遇到你的问题。

**Comment by knlvz** [comment]
那我再试试

**Comment by bettermanbao** [comment]
看你截图，应该已经成功了。

**Comment by knlvz** [comment]
现在能上国内的，但是墙外上不了，是否支持chacha20加密？

**Comment by knlvz** [comment]
果然是防火墙问题，文件gfwlist_iptables里面的命令没有被执行，我把里面的命令都执行一遍后可以上了。

是不是在shadowsocks里面忘记写这条命令了？

**Comment by bettermanbao** [comment]
这些命令会随系统重启，自动加载。
网络设置变更后，也会自动加载。

**Comment by knlvz** [comment]
嗯嗯，明白了，config\scripts\post-config.d下的gfwlist_iptables也要给个执行权限，现在路由重启后能自启了，感谢！
