### ISSUE TITLE
老大，我报告一下发现的问题

### ISSUE THREAD

**Issue by alawnchen** [bettermanbao/erx-shadowsocks-libev#3]
1. iptable是和ipset的问题，ipset创建gfwlist正常，而且通过ipset list确实可以看到gfwlist以及被添加的几条数据。但是自启动脚本启动（/etc/init.d/shadowsocks start）或者重启 ( /etc/init.d/shadowsocks restart ) 的时候iptables会输出无法找到gfwlist集合的信息。而最奇怪的一点是单独设置却成功了。
2. redsocks没启动，这个我没有细查！

下面是启动和停止时候的截图。请老大看看出了什么毛病！
![_20180322140457](https://user-images.githubusercontent.com/1811463/37753943-56e9a7c6-2dda-11e8-8172-5f5b3f3c60f9.png)
![_20180322140611](https://user-images.githubusercontent.com/1811463/37753955-653c25ba-2dda-11e8-99e3-957639cd36fd.png)
)

请老大指教

**Comment by bettermanbao** [comment]
这些提示都是正常的。
* ipset的错误是因为最新启动脚本会删除所有iptable规则，再添加，已避免添加2次相同的规则。
* redsocks和shadowsocks是2选1，默认启动shadowsocks。
* kcptun是可选的。

你先试试路由器上ip:1080的socks5代理工作是否正常，如果不正常先检查ss的配置文件有没写错。

**Comment by alawnchen** [comment]
@bettermanbao  Socket5正常  配置文件也OK 我特地在win7上面用SS客户端试了 确定配置文件没有问题
![_20180322144623](https://user-images.githubusercontent.com/1811463/37755279-d3bb32b0-2ddf-11e8-879d-44676f7fc3b0.png)

**Comment by bettermanbao** [comment]
重启一下电脑，应该就好了。
电脑上的dns缓存没有刷新。

**Comment by alawnchen** [comment]
@bettermanbao  还是不行，谢谢了。打算换个方式，我自己编译一次吧！
