### ISSUE TITLE
1.10.1 not working

### ISSUE THREAD

**Issue by lilarcor** [bettermanbao/erx-shadowsocks-libev#4]
redsocks can't start up and iptables section in /etc/init.d/shadowsocks error when restarting

**Comment by lilarcor** [comment]
also tried 1.97 hot fix, not working either

**Comment by bettermanbao** [comment]
enable redsocks by rename redsocks.conf.disable to redsocks.conf, make sure you disable shadowsocks while enabled redsocks. Because they provide same fucntion.

**Comment by bettermanbao** [comment]
iptables error is normal, just ignore it.

**Comment by lilarcor** [comment]
Thanks, I try it tomorrow
